### ISSUE TITLE
missing chapters

### ISSUE THREAD

**Issue by zrix20** [Akianonymus/mangadl-bash#1]
why all the H manhwa(+18) are missing n READMANHWA extensions?

**Comment by Akianonymus** [comment]
![Screenshot_Termux_20200808-170828_1](https://user-images.githubusercontent.com/32216346/89709053-f745ec80-d999-11ea-97d1-671733d665b9.png)

Working here.

Which one is missing ? Give a name.

**Comment by zrix20** [comment]
> ![Screenshot_Termux_20200808-170828_1](https://user-images.githubusercontent.com/32216346/89709053-f745ec80-d999-11ea-97d1-671733d665b9.png)
> 
> Working here.
> 
> Which one is missing ? Give a name.
