### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by zrix20** [Akianonymus/mangadl-bash#2]
![Screenshot_20200808-200323](https://user-images.githubusercontent.com/69387448/89710046-68919980-d9b2-11ea-9ac6-f17e10c4c08f.png)

missing H MANWHA ( ReadManwha extension)

**Comment by Akianonymus** [comment]
> ![Screenshot_20200808-200323](https://user-images.githubusercontent.com/69387448/89710046-68919980-d9b2-11ea-9ac6-f17e10c4c08f.png)
> 
> missing H MANWHA ( ReadManwha extension)

report this in tachiyomi repo, lol

**Comment by zrix20** [comment]
I already enable nsfw.

what did you mean by report this in tachiyomi?

**Comment by zrix20** [comment]
i dont the link.tachiyomi brng me here to ask some issue.

**Comment by Akianonymus** [comment]
@zrix20 https://github.com/inorichi/tachiyomi-extensions

report the issue there.

**Comment by zrix20** [comment]
They Fix problem so fast. 
Many thanks. =)
