### ISSUE TITLE
mangahub source(server) isn't working

### ISSUE THREAD

**Issue by HasanAbbadi** [Akianonymus/mangadl-bash#4]
i installed it by cloning the repo and using install.bash
but when I try to search for something the result is always like this:

--
![Screenshot from 2021-04-18 14-29-19](https://user-images.githubusercontent.com/78548167/115143922-8986b000-a052-11eb-8133-a470dae2a46e.png)

**Comment by HasanAbbadi** [comment]
oh wait, it is just the default server that was doing that.
it works fine with the -s flag, my bad.

**Comment by Akianonymus** [comment]
Opening this issue as it is valid.

**Comment by Akianonymus** [comment]
This has been fixed.

**Comment by Akianonymus** [comment]
This has been fixed.
