### ISSUE TITLE
[new provider] GMANGA(.org)

### ISSUE THREAD

**Issue by HasanAbbadi** [Akianonymus/mangadl-bash#5]
can you please try to add support to this source
I tried doing it myself, but failed horribly.
gmanga.org

**Comment by Akianonymus** [comment]
> can you please try to add support to this source
> I tried doing it myself, but failed horribly.
> gmanga.org

Will try, will take more time as I don't understand the language and google translate doesn't help properly with scraping.

**Comment by HasanAbbadi** [comment]
yeah I know, it also doesn't have a "search page" the search page is the home page itself which confused me
anyways, thank you.

**Comment by Akianonymus** [comment]
@HasanAbbadi Well, that's easy enough.

They just send a post request to their api, `https://gmanga.org/api/quick_search`.

Will push the the full implementation soon.

**Comment by HasanAbbadi** [comment]
is there something wrong?

**Comment by Akianonymus** [comment]
> is there something wrong?

Except from me being lazy, nothing really 😂

Anyway, will probably do this today or tomorrow maybe.

**Comment by Akianonymus** [comment]
Added support: https://github.com/Akianonymus/mangadl-bash/commit/cebfad8be2f888f6d9c60f6366e70b0bf807392f

Took me a while to implement the decryption process. New dependencies on jq and openssl
