### ISSUE TITLE
URL for Mangakakalot was changed

### ISSUE THREAD

**Issue by MJ0230** [Akianonymus/mangadl-bash#7]
The URL (when going to the specific manga) was changed to readmanganato.com.

The search function is still working (and displaying the URL correctly), however, directly trying to access a mange via the readmanganato.com URL is resulting in an error.

**Comment by Akianonymus** [comment]
Can you specify a little bit more ? I tried searching and opening the url and it worked fine. What was your search query ?

**Comment by MJ0230** [comment]
Sure. Let me take an example of this manga: Against the Gods. URL if I check it on Mangakakalot: https://readmanganato.com/manga-cl980168 

executing this command: 

`mangadl -d ./test/ -r 2 https://readmanganato.com/manga-cl980168`

will result in this output:

` bash-5.1# .mangadl-bash/mangadl -d ./test/ -r 2 https://readmanganato.com/manga-cl980168 `
` =============[ URL not supported. ]============= `
` ==== Time Elapsed: 0 minute(s) and 0 seconds ======= `
` bash-5.1# `

However, if I do a search for Against the name with this command:

`mangadl -d ./test/ -r 2 "against the gods"`

I get this result

` bash-5.1# .mangadl-bash/mangadl -d ./test/ -r 2 "against the gods" `                                                               
` ====[ against the gods ]==== `
` ====[ Source: manganelo ]===== `
` ====[ 2 results found ]======= `
                                                                                                                                 
`  1. Against The Gods `                                                                                                              
 `   URL: https://readmanganato.com/manga-cl980168 `                                                                                 
 `   Latest: "Against the Gods Chapter 526" `                                                                                        
 `   Updated : Sep-22-2022 16:31 `                                                                                                   
                                                                                                                                 
` 2. The King Of All `                                                                                                               
`    URL: https://readmanganato.com/manga-lk989245 `                                                                                 
`    Latest: "The King of All Chapter 89" `                                                                                          
`    Updated : Jun-27-2022 00:48 `                                                                                                   
                                                                                                                                 
` --------- Choose -------- `
` ->  `

Choosing 1. in the search is downloading correctly, but directly accessing the URL form the search is not.

**Comment by Akianonymus** [comment]
Update and check again, it should be fixed.
